import AsyncStorage from '@react-native-async-storage/async-storage';
import { sha256 } from 'js-sha256';
import DeviceInfo from 'react-native-device-info';
const defaultHeaders = { 'Content-Type': 'application/json' };

/**
 * Initiate the login process with a phone number.  Should be followed up with verifySMSCode().
 * @param {Number} phoneNumber - US phone number (WITHOUT +1) to send verification code to
 */
const loginViaSMS = async phoneNumber => {
  try {
    const res = await fetch(`https://api.sidechat.lol/v1/login_register`, {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        phone_number: `+1${phoneNumber}`,
        version: 3,
      }),
    });
    const json = await res.json();
    return json;
  } catch (err) {
    console.err(error);
    throw new Error('Failed to request SMS verification.');
  }
};

/**
 * Verify the code sent via SMS with loginViaSMS().
 * @param {Number} phoneNumber - US phone number (WITHOUT +1) that verification code was sent to
 * @param {String} code  - the verification code
 */
const verifySMSCode = async (phoneNumber, code) => {
  try {
    const res = await fetch(`https://api.sidechat.lol/v1/verify_phone_number`, {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        phone_number: `+1${phoneNumber}`,
        code: code.toUpperCase(),
      }),
    });
    const json = await res.json();
    return json;
  } catch (err) {
    console.err(err);
    throw new Error('Failed verify this code.');
  }
};

/**
 * Set the user's age
 * @param {Number} age - user's age in years
 * @param {String} registrationID  - the registration ID generated by verifySMSCode()
 */
const setAge = async (age, registrationID) => {
  if (age < 13) {
    throw new Error("You're too young to use Offsides.");
  }
  try {
    const res = await fetch(
      `https://api.sidechat.lol/v1/complete_registration`,
      {
        method: 'POST',
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          age: Number(age),
          registration_id: registrationID,
        }),
      },
    );
    const json = await res.json();
    return json;
  } catch (err) {
    console.err(err);
    throw new Error('Failed verify this code.');
  }
};

/**
 * Initiate the email setup process.  Should be followed up with checkEmailVerification().
 * @param {String} email - school email address to send verification code to
 * @param {String} token - user bearer token
 */
const registerEmail = async (email, token) => {
  try {
    const res = await fetch(
      `https://api.sidechat.lol/v2/users/register_email`,
      {
        method: 'POST',
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          email: email,
        }),
      },
    );
    const json = await res.json();
    if (json.message) {
      throw new Error(json.message);
    }
    return json;
  } catch (err) {
    console.err(error);
    throw new Error('Failed to request email verification.');
  }
};

/**
 * Check is the user's email is verified.
 * @param {String} token - user bearer token
 */
const checkEmailVerification = async token => {
  try {
    const res = await fetch(
      `https://api.sidechat.lol/v1/users/check_email_verified`,
      {
        method: 'GET',
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
      },
    );
    const json = await res.json();
    if (json.verified_email_updates_response) {
      return json.verified_email_updates_response;
    } else {
      throw new Error(json?.message || 'Email is not verified.');
    }
  } catch (err) {
    console.err(error);
    throw new Error('Email is not verified.');
  }
};

/**
 * Set the device ID based on the Android device ID
 * @param {String} token  - the user bearer token
 */
const setDeviceID = async token => {
  const id = await DeviceInfo.getAndroidId();
  const deviceID = sha256(id);
  try {
    const res = await fetch(
      `https://api.sidechat.lol/v1/register_device_token`,
      {
        method: 'POST',
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          build_type: 'release',
          bundle_id: 'com.flowerave.sidechat',
          device_token: deviceID,
        }),
      },
    );
    const json = await res.json();
    await AsyncStorage.setItem('deviceID', deviceID);
    return json;
  } catch (err) {
    console.err(err);
    throw new Error('Failed verify this code.');
  }
};

/**
 * Get updated status for user and group
 * @param {String} groupID - the group ID that the user belongs to
 * @param {String} token - the user bearer token
 * @returns
 */
const getUserAndGroup = async (groupID, token) => {
  try {
    const res = await fetch(
      `https://api.sidechat.lol/v1/updates?group_id=${groupID}`,
      {
        method: 'GET',
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
      },
    );
    const json = await res.json();
    return json;
  } catch (err) {
    console.error(err);
    throw new Error(`Failed to get posts from group.`);
  }
};

/**
 * Fetches posts from the specified category
 * @param {String} groupID
 * @param {String} token
 * @param {"hot"|"recent"|"top"} category
 * @param {String} [cursor]
 * @returns List of posts
 */
const getGroupPosts = async (groupID, token, category = 'hot', cursor) => {
  try {
    const res = await fetch(
      `https://api.sidechat.lol/v1/posts?group_id=${groupID}&type=${category}${
        cursor ? '&cursor=' + cursor : ''
      }`,
      {
        method: 'GET',
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
      },
    );
    console.log(res);
    const json = await res.json();
    return json;
  } catch (err) {
    console.error(err);
    throw new Error(`Failed to get posts from group.`);
  }
};

/**
 * Upvote or downvote, or unvote a post
 * @param {String} postID - post ID to vote on
 * @param {String} token - user bearer token
 * @param {"upvote"|"downvote"|"none"} action - whether to upvote, downvote, or reset vote
 * @returns
 */
const setVote = async (postID, token, action) => {
  try {
    const res = await fetch(`https://api.sidechat.lol/v1/posts/set_vote`, {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        post_id: postID,
        vote_status: action,
      }),
    });
    const json = await res.json();
    return json;
  } catch (err) {
    console.error(err);
    throw new Error(`Failed to change the vote on post.`);
  }
};

/**
 * Get all the commments on a post
 * @param {*} postID - post ID to get comments for
 * @param {*} token - user bearer token
 * @returns
 */
const getPostComments = async (postID, token) => {
  try {
    const res = await fetch(
      `https://api.sidechat.lol/v1/posts/comments/?post_id=${postID}`,
      {
        method: 'GET',
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
      },
    );
    const json = await res.json();
    return json.posts;
  } catch (err) {
    console.error(err);
    throw new Error(`Failed to get comments on post.`);
  }
};

export {
  loginViaSMS,
  verifySMSCode,
  setAge,
  setDeviceID,
  registerEmail,
  checkEmailVerification,
  getUserAndGroup,
  getGroupPosts,
  setVote,
  getPostComments,
};
